array_width = 90
brace_style = "PreferSameLine"
chain_width = 80
enum_discrim_align_threshold = 90
fn_call_width = 90
fn_single_line = true
format_strings = true
hard_tabs = true
imports_granularity = "Crate"
match_block_trailing_comma = true
max_width = 110
overflow_delimited_expr = true
reorder_impl_items = true
short_array_element_width_threshold = 90
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
spaces_around_ranges = true
struct_field_align_threshold = 90
struct_lit_width = 90
struct_variant_width = 90
use_field_init_shorthand = true
use_small_heuristics = "Off"
where_single_line = true
